name: Build Status
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Kind
    permissions:
      packages: read
    container:
      image: ghcr.io/jj/raku-zef-gha
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache installed dists
        uses: actions/cache@v2
        id: meta6
        with:
          path: ~/.raku/
          key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
      - name: Run tests
        run: |
          zef install .
